import React from "react";
import classnames from "classnames";
import Layout from "@theme/Layout";
import { useLocation } from "@docusaurus/router";
import useDocusaurusContext from "@docusaurus/useDocusaurusContext";
import { HtmlClassNameProvider, PageMetadata } from "@docusaurus/theme-common";

import ogImages from "../../data/ogImages.json";

// Landing pages get their own Open Graph image (generated by
// scripts/generate_og_images.js); every other page keeps the site default.
function useOgImage() {
  const { pathname } = useLocation();
  const { i18n, siteConfig } = useDocusaurusContext();
  const lang = i18n.currentLocale === "fr" ? "fr" : "en";
  const slug = pathname
    .replace(/^\/(fr|de|es)\//, "/")
    .replace(/^\/|\/$/g, "");
  // Absolute and without the locale prefix: the same URL as the Article image in
  // the structured data (getOgImageUrl).
  return ogImages.includes(slug)
    ? `${siteConfig.url}/img/og/${slug}-${lang}.jpg`
    : undefined;
}

/**
 * The shell of every "Horizon" marketing page.
 *
 * `horizon-page` lands on <html> server-side, which is how the navbar and the
 * footer (rendered outside the page wrapper by the theme) pick up the theme
 * without a flash; `horizon-page-body` carries the tokens and the scene. Both
 * are plain global classes rather than CSS-module ones so that pages keeping
 * their own stylesheet can read the tokens too. See src/css/horizon.css.
 */
function HorizonPage({ title, description, className, children }) {
  const ogImage = useOgImage();
  return (
    <HtmlClassNameProvider className="horizon-page">
      <Layout title={title} description={description}>
        {ogImage && <PageMetadata image={ogImage} />}
        <div className={classnames("horizon-page-body", className)}>
          {children}
        </div>
      </Layout>
    </HtmlClassNameProvider>
  );
}

export default HorizonPage;
